version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm-packages"
      - run: npm i
      - run: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - restore_cache:
          key: "npm-packages"
      - run: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: "npm-packages"
      - run: npm audit

workflows:
  myworkflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
  